# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GisReviewNotes
                                 A QGIS plugin
 Feature-level QA/QC annotation tool based on GeoPackage.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-06-22
        copyright            : (C) 2026 by zhangshun
        email                : 2023302051097@whu.edu.cn
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GisReviewNotes class from file GisReviewNotes.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .gis_review_notes import GisReviewNotes
    return GisReviewNotes(iface)
