# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GisReviewNotes
                                 A QGIS plugin
 Feature-level QA/QC annotation tool based on GeoPackage.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-06-22
        git sha              : $Format:%H$
        copyright            : (C) 2026 by zhangshun
        email                : 2023302051097@whu.edu.cn
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, Qt
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction
# Initialize Qt resources from file resources.py
from .resources import *

# Import the code for the DockWidget
from .gis_review_notes_dockwidget import GisReviewNotesDockWidget
import os.path

import os
import sqlite3
from qgis.core import QgsProject, QgsMessageLog, Qgis

#处理地图交互和弹出对话框所需的模块
from qgis.gui import QgsMapToolIdentifyFeature, QgsMapTool
from qgis.PyQt.QtWidgets import QInputDialog, QMessageBox, QTableWidgetItem


class GisReviewNotes:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface

        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)

        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'GisReviewNotes_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&GIS Review Notes')
        # TODO: We are going to let the user set this up in a future iteration
        self.toolbar = self.iface.addToolBar(u'GisReviewNotes')
        self.toolbar.setObjectName(u'GisReviewNotes')

        #print "** INITIALIZING GisReviewNotes"

        self.pluginIsActive = False
        self.dockwidget = None

    def init_gpkg_database(self, layer):
        """
        检查当前图层，并初始化 GeoPackage 数据库中的注释表
        """
        # 1. 检查图层是否有效
        if not layer or layer.providerType() != 'ogr':
            self.iface.messageBar().pushMessage("提示", "请先在图层树中选中一个矢量图层", level=Qgis.Warning)
            return None

        # 2. 提取数据源路径并判断是否为 gpkg
        # QGIS的source通常长这样: C:/data.gpkg|layername=roads
        source_path = layer.source().split("|")[0]
        if not source_path.endswith('.gpkg'):
            self.iface.messageBar().pushMessage("提示", "GIS Review Notes 仅支持 GeoPackage (.gpkg) 格式的图层",
                                                level=Qgis.Warning)
            return None

        # 3. 连接 SQLite 并在 GPKG 中隐式创建属性表
        try:
            conn = sqlite3.connect(source_path)
            cursor = conn.cursor()

            # 创建关联表（如果不存在）
            create_table_sql = """
            CREATE TABLE IF NOT EXISTS qa_annotations (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                layer_id TEXT NOT NULL,
                feature_id INTEGER NOT NULL,
                priority TEXT NOT NULL,
                status TEXT DEFAULT '待处理',
                comment TEXT,
                created_at DATETIME DEFAULT CURRENT_TIMESTAMP
            );
            """
            cursor.execute(create_table_sql)
            conn.commit()

            QgsMessageLog.logMessage(f"数据库表初始化成功: {source_path}", "GIS Review Notes", Qgis.Info)
            return source_path

        except sqlite3.Error as e:
            QgsMessageLog.logMessage(f"创建表失败: {e}", "GIS Review Notes", Qgis.Critical)
            return None
        finally:
            if 'conn' in locals():
                conn.close()

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('GisReviewNotes', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            self.toolbar.addAction(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action


    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/gis_review_notes/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'C:\\Users\\29590\\AppData\\Roaming\\QGIS\\QGIS3\\profiles\\default\\python\\plugins'),
            callback=self.run,
            parent=self.iface.mainWindow())

    #--------------------------------------------------------------------------

    def onClosePlugin(self):
        """Cleanup necessary items here when plugin dockwidget is closed"""

        #print "** CLOSING GisReviewNotes"

        # disconnects
        self.dockwidget.closingPlugin.disconnect(self.onClosePlugin)

        # remove this statement if dockwidget is to remain
        # for reuse if plugin is reopened
        # Commented next statement since it causes QGIS crashe
        # when closing the docked window:
        # self.dockwidget = None

        self.pluginIsActive = False


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""

        #print "** UNLOAD GisReviewNotes"

        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&GIS Review Notes'),
                action)
            self.iface.removeToolBarIcon(action)
        # remove the toolbar
        del self.toolbar

    #--------------------------------------------------------------------------

    def run(self):
        """Run method that loads and starts the plugin"""

        if not self.pluginIsActive:
            self.pluginIsActive = True

            #print "** STARTING GisReviewNotes"

            # dockwidget may not exist if:
            #    first run of plugin
            #    removed on close (see self.onClosePlugin method)
            if self.dockwidget == None:
                # Create the dockwidget (after translation) and keep reference
                self.dockwidget = GisReviewNotesDockWidget()

            # connect to provide cleanup on closing of dockwidget
            self.dockwidget.closingPlugin.connect(self.onClosePlugin)

            # show the dockwidget
            # TODO: fix to allow choice of dock location
            self.iface.addDockWidget(Qt.LeftDockWidgetArea, self.dockwidget)
            self.dockwidget.show()
            # 绑定 "开启标绘模式" 按钮的点击事件
            self.dockwidget.btnNoteMode.toggled.connect(self.toggle_review_mode)
            # 绑定 "刷新" 按钮的点击事件
            self.dockwidget.btnRefresh.clicked.connect(self.load_annotations)

    def toggle_review_mode(self, checked):
        """处理标绘模式按钮的开关逻辑"""
        canvas = self.iface.mapCanvas()

        if checked:
            # 当按钮被按下时
            layer = self.iface.activeLayer()
            db_path = self.init_gpkg_database(layer)

            if db_path:
                # 数据库初始化成功，激活自定义地图工具
                self.map_tool = ReviewMapTool(canvas, layer, db_path)
                canvas.setMapTool(self.map_tool)
                self.iface.messageBar().pushMessage("提示", "标绘模式已开启，请在地图上点击目标要素", level=Qgis.Success)
            else:
                # 初始化失败，把按钮弹起来
                self.dockwidget.btnNoteMode.setChecked(False)
        else:
            # 当按钮被弹起时，恢复 QGIS 默认的漫游(平移)工具
            canvas.unsetMapTool(self.map_tool)
            self.iface.actionPan().trigger()
            self.iface.messageBar().pushMessage("提示", "标绘模式已关闭", level=Qgis.Info)

    def load_annotations(self):
        """从 GeoPackage 数据库读取注释并填充到表格中"""
        layer = self.iface.activeLayer()
        if not layer or layer.providerType() != 'ogr':
            return

        source_path = layer.source().split("|")[0]
        if not source_path.endswith('.gpkg'):
            return

        try:
            conn = sqlite3.connect(source_path)
            cursor = conn.cursor()

            # 查询当前图层的所有注释
            layer_id = layer.id()
            cursor.execute("""
                SELECT id, feature_id, priority, status, comment, created_at 
                FROM qa_annotations 
                WHERE layer_id = ? 
                ORDER BY created_at DESC
            """, (layer_id,))

            rows = cursor.fetchall()

            # 设置表格的基础格式
            table = self.dockwidget.tableNotes
            table.setRowCount(0)  # 清空旧数据
            table.setColumnCount(6)
            table.setHorizontalHeaderLabels(["记录ID", "要素ID", "优先级", "状态", "注释内容", "创建时间"])

            # 将数据逐行填入表格
            for row_idx, row_data in enumerate(rows):
                table.insertRow(row_idx)
                for col_idx, cell_data in enumerate(row_data):
                    item = QTableWidgetItem(str(cell_data))
                    # 设置为只读，防止用户直接在表格里乱改
                    item.setFlags(item.flags() ^ Qt.ItemIsEditable)
                    table.setItem(row_idx, col_idx, item)

            self.iface.messageBar().pushMessage("提示", f"成功加载 {len(rows)} 条注释数据", level=Qgis.Success)

        except sqlite3.Error as e:
            # 如果表还不存在，不报错，直接跳过
            pass
        finally:
            if 'conn' in locals():
                conn.close()


class ReviewMapTool(QgsMapToolIdentifyFeature):
    def __init__(self, canvas, layer, db_path):
        super().__init__(canvas, layer)
        self.canvas = canvas
        self.layer = layer
        self.db_path = db_path
        # 设置鼠标光标为十字准星
        self.setCursor(Qt.CrossCursor)

    def canvasReleaseEvent(self, e):
        """当用户在地图上点击并释放鼠标时触发"""
        # 1. 尝试识别点击位置的要素
        results = self.identify(e.x(), e.y(), [self.layer], QgsMapToolIdentifyFeature.TopDownStopAtFirst)

        if not results:
            self.canvas.scene().removeItem(self)
            return

        # 获取点中的第一个要素
        feature = results[0].mFeature
        feature_id = feature.id()
        layer_id = self.layer.id()

        # 2. 弹出简易对话框让用户输入注释
        comment, ok1 = QInputDialog.getText(None, "添加注释", f"正在为要素(ID:{feature_id})添加注释:\n请输入内容:")
        if not ok1 or not comment.strip():
            return

        # 弹出简易对话框选择优先级
        priority_items = ["高", "中", "低"]
        priority, ok2 = QInputDialog.getItem(None, "选择优先级", "请选择该问题的优先级:", priority_items, 0, False)
        if not ok2:
            return

        # 3. 将数据写入 GeoPackage 的 qa_annotations 表
        self.save_annotation(layer_id, feature_id, priority, comment)

    def save_annotation(self, layer_id, feature_id, priority, comment):
        """将用户输入写入 SQLite 数据库"""
        try:
            conn = sqlite3.connect(self.db_path)
            cursor = conn.cursor()
            sql = """
                INSERT INTO qa_annotations (layer_id, feature_id, priority, comment) 
                VALUES (?, ?, ?, ?)
            """
            cursor.execute(sql, (layer_id, feature_id, priority, comment))
            conn.commit()
            QMessageBox.information(None, "成功", "注释已保存并关联至该要素！")
        except sqlite3.Error as err:
            QMessageBox.critical(None, "数据库错误", f"保存失败: {err}")
        finally:
            if 'conn' in locals():
                conn.close()